src/autores/urls.py
from django.urls import path
from .views import (
    autores_list, 
    autor_por_id, 
    AutorCreateView, 
    AutorUpdateView, 
    autor_cambiar_estado,
    autor_frases,
    autores_buscar )


app_name = 'autores'

urlpatterns = [
    path('', autores_list, name='autores_list'),
    path('<int:id>/', autor_por_id, name='autor_por_id'),
    path('crear/', AutorCreateView.as_view(), name='autores_crear'),
    # path('crear_funcion/', autor_crear),
    path('modificar/<int:pk>/', AutorUpdateView.as_view(), name='autores_modificar'),
    path('cambiar_estado/<int:id>/', autor_cambiar_estado, name='autor_cambiar_estado'),
    path('frases/<int:id>/', autor_frases, name='autor_frases'),
    path('buscar/', autores_buscar, name='buscar')
]

src/autores_prueba/urls.py
from django.urls import path
from .views import primera_vista, segunda_vista, vista_html

app_name = 'autores_prueba'

urlpatterns = [
    path("primera/", primera_vista, name='primera_vista'),
    path("segunda/", segunda_vista, name='segunda_vista'),
    path("html/<str:dinamico>/<int:numero>/", vista_html, name='vista_html'),
]

src/autores_quotes/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('inicio.urls', namespace='inicio')),
    path("prueba/", include('autores_prueba.urls', namespace='autores_prueba')),
    path("autores/", include('autores.urls', namespace='autores')),
    path("frases/", include('frases.urls', namespace='frases')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/frases/urls.py
from django.urls import path
from .views import FrasesListView, FrasesCreateView, FrasesUpdateView

app_name = 'frases'

urlpatterns = [
    path('', FrasesListView.as_view(), name='frases_list'),
    path('crear/', FrasesCreateView.as_view(), name='frases_crear'),
    path('edit/<int:pk>/', FrasesUpdateView.as_view(), name='frases_modificar'),
]

src/inicio/urls.py
from django.urls import path
from .views import dashboard

app_name = 'inicio'

urlpatterns = [
    path('', dashboard, name='inicio'),
]

src/autores/models.py
from django.db import models
from django.urls import reverse


# Create your models here.
class Autor(models.Model):
    """ Clase que representa a los autores de las frases """
    nombre = models.CharField(max_length=50)
    fecha_nacimiento = models.DateField()
    fecha_fallecimiento = models.DateField(null=True, blank=True)
    creado = models.DateTimeField(auto_now_add=True)
    modificado = models.DateTimeField(auto_now=True)
    activo = models.BooleanField(default=True)
    foto = models.ImageField(upload_to='autores_img/', default='autor_generico.png')

    def __str__(self):
        return F"{self.nombre.upper()}"
    
    def get_absolute_url(self):
        return reverse("autores:autor_por_id", kwargs={"id": self.id})
    

src/frases/models.py
from django.db import models
from autores.models import Autor

# Create your models here.
class Frase(models.Model):
    """
    Representa una frase dicha por uno de los autores
    """
    autor = models.ForeignKey(Autor, on_delete=models.CASCADE)
    contenido = models.CharField(max_length=200)
    fecha = models.DateField(blank=True, null=True)
    activa = models.BooleanField(default=True)

    def __str__(self):
        return F"{self.contenido}"

src/inicio/models.py
from django.db import models

# Create your models here.

src/autores/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from django.urls import reverse
from django.views.generic.edit import CreateView, UpdateView
from .models import Autor 

# Create your views here.
def autores_list(request):
    autores = Autor.objects.all()
    return render(request, 'autores/autores_list.html', {'autores': autores})


def autor_por_id(request, id):
    autor = get_object_or_404(Autor, id=id)
    return render(request, 'autores/autores_id.html', {'autor': autor})


# def autor_crear(request):
#     if request.method == 'GET':
#         return HttpResponse("Llegué con método GET")

#     if request.method == 'POST':
#         return HttpResponse("Llegué con método POST")

class AutorCreateView(CreateView):
    model = Autor
    fields = ['nombre', 'fecha_nacimiento', 'fecha_fallecimiento', 'activo', 'foto']
    template_name = 'autores/autores_edit.html'
    success_url = 'http://localhost:8000/autores/'


class AutorUpdateView(UpdateView):
    model = Autor
    fields = ['nombre', 'fecha_nacimiento', 'fecha_fallecimiento', 'activo', 'foto']
    template_name = 'autores/autores_edit.html'
    success_url = 'http://localhost:8000/autores/'


def autor_cambiar_estado(request, id):
    autor = get_object_or_404(Autor, id=id)
    autor.activo = not(autor.activo)
    autor.save()
    return redirect("autores:autores_list")


def autor_frases(request, id):
    autor = get_object_or_404(Autor, id=id)
    frases = autor.frase_set.all()
    return render(request, 'frases/frases_list.html', {'lista_de_frases': frases})


def autores_buscar(request):
    if request.method == 'POST':
        a_buscar = request.POST.get('buscar')
        resultado = Autor.objects.filter(nombre__contains=a_buscar)
        print(resultado)
        return redirect("http://localhost:8000/")

src/autores_prueba/views.py
from django.shortcuts import render
from django.http import HttpResponse


# Create your views here.
def primera_vista(request):
    return HttpResponse(content="Hola desde Django!!!!")

def segunda_vista(request):
    return HttpResponse(content="<h1>ESTA ES LA SEGUNDA VISTA</h1>")

def vista_html(request, dinamico, numero):
    return render(request, 'prueba/prueba_mensajes.html', 
            { 'valor': dinamico, 
              'anios': numero })

src/frases/views.py
from django.shortcuts import render
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView
from .models import Frase


# Create your views here.
class FrasesListView(generic.ListView):
    queryset = Frase.objects.all()
    template_name = 'frases/frases_list.html'
    context_object_name = 'lista_de_frases'


class FrasesCreateView(CreateView):
    model = Frase
    # fields = '__all__'
    fields = ['autor', 'contenido', 'fecha']
    template_name = 'frases/frases_edit.html'
    success_url = 'http://localhost:8000/frases/'

class FrasesUpdateView(UpdateView):
    model = Frase
    fields = '__all__'
    template_name = 'frases/frases_edit.html'
    success_url = 'http://localhost:8000/frases/'   

src/inicio/views.py
from django.shortcuts import render

# Create your views here.
def dashboard(request):
    return render(request, 'inicio/dashboard.html')

src/templates/autores/autores_edit.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<div class="alert alert-warning" role="alert">

    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <table class="table table-dark table-striped">
            <tr>
                <td>Nombre</td>
                <td>{{form.nombre}}</td>
            </tr>
            <tr>
                <td>Fecha de Nacimiento</td>
                <td>{{form.fecha_nacimiento}}</td>                
            </tr>
            <tr>
                <td>Fecha de Fallecimiento</td>
                <td>{{form.fecha_fallecimiento}}</td>                
            </tr>
            <tr>
                <td>Activo? </td>
                <td>{{form.activo}}</td>                
            </tr>
            <tr>
                <td>Imagen </td>
                <td>{{form.foto}}</td>  
            </tr>
        </table>
        <button type="submit" class="btn btn-success">Guardar</button>
    </form>

    {% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
            <p> {{ error }} </p>
        {% endfor %}
    {% endfor %}
    {% endif %}
    </ul>
</div>
{% endblock content %}

src/templates/autores/autores_id.html
{% extends "base.html" %}

{% block content %}

    {{autor.nombre}}
    {{autor.fecha_nacimiento}}
    {{autor.fecha_fallecimiento}}

    <button type="button" class="btn btn-outline-danger">
        <a href="{% url 'autores:autores_list' %}"> -- Volver al Listado -- </a>
    </button>

{% endblock content %}

src/templates/autores/autores_list.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<h2>Lista de Autores</h2>

<table class="table table-hover">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Nombre</th>
        <th scope="col">Fecha Nacimiento</th>
        <th scope="col">Fecha Fallecimiento</th>
        <th scope="col">Activo</th>
        <th scope="col">Frases</th>
        <th scope="col">Acciones</th>
      </tr>
    </thead>
    <tbody>
        {% for autor in autores %}
      <tr>
        <th scope="row">
          <a href="{% url 'autores:autor_por_id' autor.id %}">
            <img src="{{ autor.foto.url }}" width="50px" />
          </a>
        </th>
        <td>{{autor.nombre}}</td>
        <td>{{autor.fecha_nacimiento}}</td>
        <td>{{autor.fecha_fallecimiento}}</td>
        <td>
          {% if autor.activo %}
            <img src="{% static 'img/verde.png' %}" alt="ACTIVO" width="50px" />
          {% else %}
            <img src="{% static 'img/rojo.png' %}" alt="INACTIVO" width="50px" />
          {% endif %}
        </td>
        <td>
          {% if autor.frase_set.count > 0%}
            {{autor.frase_set.count}}
            <a href="{% url 'autores:autor_frases' autor.pk %}">
              <img src="{% static 'img/citar.png' %}" alt="CITAS" width="50px" />
            </a>
          {% endif %}
        </td>
        <td>
          <a href="{% url 'autores:autores_modificar' autor.pk %}">
           <img src="{% static 'img/editar.png' %}" alt="MODIFICAR" width="50px" />
          </a>

          <a href="{% url 'autores:autor_cambiar_estado' autor.pk %}">
            {% if autor.activo %}
              <img src="{% static 'img/apagar.png' %}" alt="DESACTIVAR" width="50px" />
            {% else %}
              <img src="{% static 'img/encender.png' %}" alt="ACTIVAR" width="50px" />
            {% endif %}
          </a>
        </td>
      </tr>
        {% endfor %}
    </tbody>
  </table>


{% endblock content %}

src/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Super PROYECTO DE FLAVIO</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  </head>
  <body>
    <div class="container">

      <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'inicio:inicio' %}">Mi Super Django Project 2.0</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Menu de busqueda
                </a>
                <ul class="dropdown-menu">
                  <li>
                    <a class="dropdown-item" href="{% url 'autores:autores_list' %}">Listado de Autores</a>
                  </li>
                  <li>
                    <a class="dropdown-item" href="{% url 'frases:frases_list' %}">Listado de Frases</a>
                  </li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href="#">Something else here</a></li>
                </ul>
              </li>
            </ul>
            <form class="d-flex" role="search" method="post" action="{% url 'autores:buscar' %}">
              {% csrf_token %}
              <input class="form-control me-2" type="search" placeholder="Buscar un autor" aria-label="Search" name="buscar">
              <button class="btn btn-outline-success" type="submit">Buscar</button>
            </form>
          </div>
        </div>
      </nav>


        {% block content %}
        {% endblock content %}
    </div>  
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>

src/templates/frases/frases_edit.html
{% extends "base.html" %}

{% block content %}

<form method="post">
    {% csrf_token %} 
    {{ form.as_p }}
    <button type="submit">Guardar</button>
</form>


{% endblock content %}

src/templates/frases/frases_list.html
{% extends "base.html" %}
{% load static %}

{% block content %}

    {% for object in lista_de_frases %}

    <ul>
        <li>
            <img src="{% static 'img/cita.png' %}" width="60px" />
            {{object}} 
            {% if object.activa %}
                [-- ACTIVA --]
            {% else %}
                [ -- INACTIVA --]
            {% endif %}
        </li>
    </ul>

    {% endfor %}

{% endblock content %}

src/templates/inicio/dashboard.html
{% extends "base.html" %}

{% block content %}

<h1>DASHBOARD DE MI APLICACIÓN</h1>

{% endblock content %}

src/templates/prueba/prueba_mensajes.html
{% extends "base.html" %}

{% block content %}

SOY UN TEMPLATE HEREDADO!!!!

Bienvenido {{ valor }}
Tienes {{ anios }} años.

{% endblock content %}